import os
import sys
import json
import glob
import time
import subprocess
import requests
from datetime import datetime, timedelta, timezone
from bs4 import BeautifulSoup

def schedule_post(text, image_url, schedule_time):
    integration_ids = os.environ.get("POSTIZ_INTEGRATION_ID", "").split(",")
    # The user wants to post to instagram which is cmpmxrs5500aeql0yts19etm7
    # For now, we only post these caricatures to Instagram.
    # The user specifically mentioned "post one to instagram" previously, and "the other ones... schedule to go across the day ET... to have 1 of the template posts..3 of these."
    # Let's post to Instagram only for caricatures if we want to be safe, or we can use the environment variable which is already set to the two integration IDs.
    
    for int_id in integration_ids:
        int_id = int_id.strip()
        if not int_id: continue
        
        # In the context, integration "cmpmxrs5500aeql0yts19etm7" is Instagram.
        if int_id != "cmpmxrs5500aeql0yts19etm7": 
            continue # ONLY post caricatures to IG
            
        print(f"Scheduling caricature post for integration {int_id} at {schedule_time}...")
        cmd = [
            "postiz", "posts:create",
            "-c", text,
            "-s", schedule_time,
            "-i", int_id
        ]
        if image_url:
            # We must use settings for Instagram posts if the image is from postiz uploads
            cmd.extend(["-m", image_url, "--settings", '{"post_type":"post"}'])
            
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"Successfully scheduled for {int_id}")
        else:
            print(f"Failed to schedule for {int_id}: {result.stderr}")

def upload_to_postiz(image_path):
    print(f"Uploading {image_path} to Postiz...")
    cmd = ["postiz", "upload", image_path]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        print("Upload successful!")
        try:
            json_str = result.stdout[result.stdout.find('{'):result.stdout.rfind('}')+1]
            data = json.loads(json_str)
            return data.get("path")
        except Exception as e:
            print(f"Could not parse upload URL: {e}")
            return None
    else:
        print(f"Upload failed: {result.stderr}")
        return None

def generate_image_with_gemini(prompt, save_path):
    print(f"Generating image with Gemini...")
    try:
        from google import genai
        from google.genai import types
        client = genai.Client()
        
        response = client.models.generate_images(
            model='imagen-3.0-generate-002',
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="1:1"
            )
        )
        
        if response.generated_images and len(response.generated_images) > 0:
            image_bytes = response.generated_images[0].image.image_bytes
            with open(save_path, "wb") as f:
                f.write(image_bytes)
            print(f"Successfully generated and saved caricature to: {save_path}")
            return True
        else:
            print("No images were generated by Gemini.")
            return False
            
    except Exception as e:
        print(f"Error generating image with Gemini: {e}")
        return False

def main():
    date_str = datetime.now().strftime("%Y-%m-%d")
    json_path = os.path.join("NewsReport", f"{date_str}-deals.json")
    
    if not os.path.exists(json_path):
        print(f"No deals JSON found for today ({json_path}). Run fetch_and_upload.py first.")
        sys.exit(0)
        
    with open(json_path, "r") as f:
        deals = json.load(f)
        
    # We want up to 3 founder spotlights
    deals_with_images = [d for d in deals if d.get("article_image")]
    top_deals = deals_with_images[:3]
    
    if not top_deals:
        print("No deals with images found today.")
        sys.exit(0)
        
    master_prompt = (
        "A stylized 2D digital illustration caricature of the founder of {startup}. "
        "The style features sharp, angular geometry, stylized proportions (slightly exaggerated facial features), "
        "flat but vibrant shading, bold crisp inking lines with sketch-like construction lines faintly visible. "
        "Use an earthy, warm color palette (tans, browns, creams). "
        "The shading should have hard edges, giving a slightly blocky, graphic-novel aesthetic. "
        "The background should be a simple, warm-toned gradient."
    )
    
    # Schedule across the day ET. Let's say 12pm, 3pm, 6pm ET.
    # Current runner is UTC. UTC is 4 or 5 hours ahead of ET depending on daylight savings.
    # We will just schedule them spaced out starting in 2 hours from now for simplicity in a global runner.
    
    base_time = datetime.now(timezone.utc) + timedelta(hours=2)
    
    for i, deal in enumerate(top_deals):
        startup = deal.get("startup", "a startup")
        prompt = master_prompt.format(startup=startup)
        
        save_path = os.path.join("NewsReport", "images", f"{date_str}-caricature-{i}.jpg")
        
        if generate_image_with_gemini(prompt, save_path):
            uploaded_url = upload_to_postiz(save_path)
            if uploaded_url:
                text = f"🚀 Founder Spotlight: The visionary behind {startup}!\n\n{deal.get('summary', '')}\n\n#FounderSpotlight #{startup.replace(' ', '')} #VentureCapital #Startups"
                
                # Stagger by 3 hours each
                schedule_dt = base_time + timedelta(hours=3*i)
                schedule_time_str = schedule_dt.strftime("%Y-%m-%dT%H:%M:%SZ")
                
                schedule_post(text, uploaded_url, schedule_time_str)

if __name__ == "__main__":
    main()
